source('E:/RNA-seq/0/program/RNAseq_downstream_function.R')
data.dir <- 'E:/RNA-seq/03/counts'     # Directory containing raw gene-level count data generated by featureCounts
data.name <- 'gene_counts.txt'                # Gene count matrix file (rows = genes, columns = samples)
sample.info <- 'sample_info.xlsx'             # Sample metadata file containing sample information (e.g. sample ID, sample name, condition, batch, replicate)
result.dir <- 'E:/liuhao/RNA-seq/03/result'   # Directory of output data 

# Please note that the order of samples in the gene_counts.txt file must match the order in the sample_info.xlsx file. You can manually adjust the sample information to ensure consistency.
RNA_deg_results <- run_DESeq2(
  data.dir = data.dir,
  count_file = data.name,
  sample_info_file = sample.info,   
  group_col = "condition", # Column in sample_info containing group/condition info
  control_level = "HK2",   # Reference/control group for comparison
  species = 'human',       # human or mouse
  select = 'padj',         # Criterion for selecting DE genes: 'pvalue' or 'padj'
  cut_off_pvalue = 0.05,   # Significance threshold (pvalue or padj) 
  cut_off_logFC = 1        # Threshold for log2 fold change
)

dds <- RNA_deg_results$dds
deg <- RNA_deg_results$DEG
# save data
write.table(deg,file=file.path(result.dir, "diff_genes.txt"),row.names = TRUE,col.names = TRUE,sep = '\t')

# PCA plot
result_PCA <- plot_PCA(dds,data.dir = data.dir,sample_info_file = sample.info)

# save plot
ggsave(file=file.path(result.dir,"sample_PCA.pdf"), plot = result_PCA,
       width = 8, height = 6, units = "in")

# Volcano plot of DEGs
result_volcanoplot <- plot_volcanoplot(diff_data = deg, cut_off_pvalue = 0.05, cut_off_logFC = 1,num=3)
# save plot
ggsave(file=file.path(result.dir,"volcanoplot.pdf"), plot = result_volcanoplot,
       width = 6, height = 6, units = "in")

# DEGs heatmap
result_heatmap <- plot_heatmap(data.dir = data.dir,
                               count_file = data.name,
                               sample_info_file = sample.info,
                               gene_list = deg$external_gene_name)

# save plot
ggsave(file=file.path(result.dir,"heatmap.pdf"), plot = result_heatmap,
       width = 4, height = 6, units = "in")

# DEGs GO analysis
GO_results <- GO_enrichment(deg$external_gene_name,species='human',cut_off_pvalue=0.05,showNum=10)
go.data <- GO_results$data
go.data.plot <- GO_results$plot
write.table(go.data,file=file.path(result.dir,  "GO results.txt"),sep="\t",quote=F,row.names = TRUE)
ggsave(file=file.path(result.dir,"GO_dotplot.pdf"), plot = go.data.plot,
       width = 8, height = 6, units = "in")

# DEGs KEGG analysis
KEGG_results <- KEGG_enrichment(deg$external_gene_name,species='human',cut_off_pvalue=0.05,showNum=10)
kegg.data <- KEGG_results$data
kegg.data.plot <- KEGG_results$plot
write.table(kegg.data,file=file.path(result.dir,  "KEGG results.txt"),sep="\t",quote=F,row.names = TRUE)
ggsave(file=file.path(result.dir,"KEGG_dotplot.pdf"), plot = kegg.data.plot,

       width = 8, height = 6, units = "in")
