source('E:/RNA-seq/03/program/RNAseq_downstream_function.R')
data.dir <- 'E:/RNA-seq/03/counts'     # Directory containing raw gene-level count data generated by featureCounts
data.name <- 'gene_counts.txt'                # Gene count matrix file (rows = genes, columns = samples)
sample.info <- 'sample_info.xlsx'             # Sample metadata file containing sample information (e.g. sample ID, sample name, condition, batch, replicate)
gene_info <- 'geneInfo.tab'
result.dir <- 'E:/RNA-seq/03/result/00'   # Directory of output data 


# step1 read data

## read count matrix
counts <- read.table(file.path(data.dir, data.name),header = TRUE,row.names = 1,sep = "\t",check.names = FALSE)
## readsample information
sample_info <- read_excel(file.path(data.dir,sample.info))
sample_info <- as.data.frame(sample_info)
rownames(sample_info) <- sample_info$sample_name

## rename sample name 
## 请一定要注意先修改表达矩阵中的样本名称，确保和sample_info表中的sample_name中的名称一致
new_names <- sample_info$sample_name
colnames(counts)[6:ncol(counts)] <- new_names

# Please note that the order of samples in the gene_counts.txt file must match the order in the sample_info.xlsx file. You can manually adjust the sample information to ensure consistency.
exp <- counts[,6:ncol(counts)]

# filter
exp <- filter_counts(data = exp,min_count = 6)

# change gene_name
gene_name <- read.table(file.path(data.dir, gene_info),skip = 1)
colnames(gene_name) = c('ensembl_id','gene_id','gene_type')
exp = merge(gene_name,exp,by.x='ensembl_id',by.y='row.names')
exp$gene_id = make.unique(as.character(exp$gene_id), sep = ".")
rownames(exp) = exp$gene_id
exp = exp[,-c(1:3)]

RNA_deg_results <- run_DESeq2(
  counts = exp,
  coldata = sample_info,
  design = ~ condition,               # Column in sample_info containing group/condition info
  control_level = "HK2",            # Reference/control group for comparison
  count.filter = 0,                 # Reference/control group for comparison
  pvalue_type = 'padj',             # Criterion for selecting DE genes: 'pvalue' or 'padj'
  cut_off_pvalue = 0.05,            # Significance threshold (pvalue or padj) 
  cut_off_logFC = 1                 # Threshold for log2 fold change
)

dds <- RNA_deg_results$dds
res <- RNA_deg_results$res
deg <- RNA_deg_results$DEG
# save data
save(file=file.path(result.dir, "RNA_deg_results.RData"))
write.table(deg,file=file.path(result.dir, "diff_genes.txt"),row.names = TRUE,col.names = TRUE,sep = '\t')

# PCA plot
result_PCA <- plot_PCA(dds,intgroup = 'condition')
result_PCA$plot
# save plot
ggsave(file=file.path(result.dir,"sample_PCA.pdf"), plot = result_PCA$plot,
       width = 6, height = 4, units = "in")

# Volcano plot of DEGs
result_volcanoplot <- plot_volcanoplot(diff_data = deg, cut_off_pvalue = 0.05, cut_off_logFC = 1,num=3, pvalue_type='padj')
# save plot
ggsave(file=file.path(result.dir,"volcanoplot.pdf"), plot = result_volcanoplot,
       width = 6, height = 6, units = "in")

# DEGs heatmap
result_heatmap <- plot_heatmap(data = dds,
                               coldata = sample_info,
                               gene_list = deg$gene_id,
                               show_gene_name = FALSE)
result_heatmap
# save plot
ggsave(file=file.path(result.dir,"heatmap.pdf"), plot = result_heatmap$plot,
       width = 4, height = 6, units = "in")

# DEGs GO analysis
GO_results <- GO_enrichment(deg$gene_id,species='human',cut_off_pvalue=0.05,showNum=10, pvalue_type='p.adjust')  # 'p.adjust' OR 'pvalue'
go.data <- GO_results$data 
go.data.plot <- GO_results$plot
write.table(go.data,file=file.path(result.dir,  "GO results.txt"),sep="\t",quote=F,row.names = TRUE)
ggsave(file=file.path(result.dir,"GO_dotplot.pdf"), plot = go.data.plot,
       width = 8, height = 6, units = "in")

# DEGs KEGG analysis
KEGG_results <- KEGG_enrichment(deg$gene_id,species='human',cut_off_pvalue=0.05,showNum=10, pvalue_type='p.adjust')
kegg.data <- KEGG_results$data
kegg.data.plot <- KEGG_results$plot
write.table(kegg.data,file=file.path(result.dir,  "KEGG results.txt"),sep="\t",quote=F,row.names = TRUE)
ggsave(file=file.path(result.dir,"KEGG_dotplot.pdf"), plot = kegg.data.plot,
       width = 8, height = 6, units = "in")
